# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Aktualności"
  url = "#posts"
  weight = 20

[[main]]
  name = "Rozwiązania"  #my add
  url = "#about"
  identifier = "product"  #my add
  weight = 30

[[main]]
  name = "Do pobrania"
  url = "cimco/do-pobrania"
  weight = 40

  [[main]]
    name = "Wersja DEMO"
    url = "cimco/wersja_demo"
    weight = 50

[[main]]
  name = "Kontakt"
# parent = "project"   #my add
  url = "#contact"
  weight = 60

[[main]]
  name = "CIMCO Edit"
  parent = "product"   #my add
  url = "cimco/edit"
  weight = 70

[[main]]
  name = "CIMCO CNC-Calc"
  parent = "product"   #my add
  url = "cimco/CNC-calc"
  weight = 80

[[main]]
  name = "CIMCO DNC-MAX"
  parent = "product"   #my add
  url = "cimco/cimco-dnc"
  weight = 90

[[main]]
  name = "CIMCO MDC-MAX"
  parent = "product"   #my add
  url = "cimco/cimco-mdc"
  weight = 100

[[main]]
  name = "CIMCO NC-Base"
  parent = "product"   #my add
  url = "cimco/NC-base"
  weight = 110


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
